### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UnixCro** [simonfarah/RestAPI#1]
```
Please insert a number from the list : 1

--------------------------------------
/usr/local/bin/tiktok-bot:184: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(PATH)
Traceback (most recent call last):
  File "/usr/local/bin/tiktok-bot", line 185, in <module>
    driver.get("https://zefoy.com/")
  File "/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 437, in get
    self.execute(Command.GET, {'url': url})
  File "/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: cannot determine loading status
from target frame detached
  (Session info: chrome=101.0.4951.64)
Stacktrace:
0   chromedriver                        0x0000000104f5c9a0 chromedriver + 4426144
1   chromedriver                        0x0000000104ef6798 chromedriver + 4007832
2   chromedriver                        0x0000000104b52b94 chromedriver + 191380
3   chromedriver                        0x0000000104b3f718 chromedriver + 112408
4   chromedriver                        0x0000000104b3e9fc chromedriver + 109052
5   chromedriver                        0x0000000104b3ee98 chromedriver + 110232
6   chromedriver                        0x0000000104b455e0 chromedriver + 136672
7   chromedriver                        0x0000000104b3ff30 chromedriver + 114480
8   chromedriver                        0x0000000104b4048c chromedriver + 115852
9   chromedriver                        0x0000000104b40280 chromedriver + 115328
10  chromedriver                        0x0000000104b3f8f0 chromedriver + 112880
11  chromedriver                        0x0000000104b3e9fc chromedriver + 109052
12  chromedriver                        0x0000000104b3ee98 chromedriver + 110232
13  chromedriver                        0x0000000104b5b97c chromedriver + 227708
14  chromedriver                        0x0000000104b55244 chromedriver + 201284
15  chromedriver                        0x0000000104b54f70 chromedriver + 200560
16  chromedriver                        0x0000000104b55484 chromedriver + 201860
17  chromedriver                        0x0000000104b4c810 chromedriver + 165904
18  chromedriver                        0x0000000104b4ce74 chromedriver + 167540
19  chromedriver                        0x0000000104b3ff30 chromedriver + 114480
20  chromedriver                        0x0000000104b4048c chromedriver + 115852
21  chromedriver                        0x0000000104b40280 chromedriver + 115328
22  chromedriver                        0x0000000104b3f8f0 chromedriver + 112880
23  chromedriver                        0x0000000104b3e9fc chromedriver + 109052
24  chromedriver                        0x0000000104b3ee98 chromedriver + 110232
25  chromedriver                        0x0000000104b4bf98 chromedriver + 163736
26  chromedriver                        0x0000000104b5929c chromedriver + 217756
27  chromedriver                        0x0000000104b3f13c chromedriver + 110908
28  chromedriver                        0x0000000104b58f14 chromedriver + 216852
29  chromedriver                        0x0000000104baa95c chromedriver + 551260
30  chromedriver                        0x0000000104b76cf4 chromedriver + 339188
31  chromedriver                        0x0000000104f337d0 chromedriver + 4257744
32  chromedriver                        0x0000000104f37580 chromedriver + 4273536
33  chromedriver                        0x0000000104f3b6c4 chromedriver + 4290244
34  chromedriver                        0x0000000104f37cf8 chromedriver + 4275448
35  chromedriver                        0x0000000104f17b38 chromedriver + 4143928
36  chromedriver                        0x0000000104f4f21c chromedriver + 4370972
37  chromedriver                        0x0000000104f4f380 chromedriver + 4371328
38  chromedriver                        0x0000000104f63154 chromedriver + 4452692
39  libsystem_pthread.dylib             0x000000018e3e14ec _pthread_start + 148
40  libsystem_pthread.dylib             0x000000018e3dc2d0 thread_start + 8
```

**Comment by simonfarah** [comment]
That's not how GitHub works smart guy.

**Comment by UnixCro** [comment]
If they hadn't locked their project so that someone could write something there, I wouldn't have written into another project to describe the situation. They block a road to the only supermarket and wonder why others are trying to reach it by other means.

**Comment by simonfarah** [comment]
The repo is archived for a reason. But looks like someone can't read or
know how to use github.

**Comment by UnixCro** [comment]
If I didn't use your project, I would have slapped you long ago for your disrespectful statements.
